services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: srhr-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: srhr_platform
      POSTGRES_USER: srhr_user
      POSTGRES_PASSWORD: srhr_dev_password
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: srhr-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  pgdata:
